org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=false
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configureondemand=true
# Optimization: Enable Gradle Build Cache
org.gradle.caching=true
